#!/usr/bin/env python3
"""Convert original Blender-readable scene descriptors to compact static C++ data."""

from __future__ import annotations

import json
import math
import struct
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "scene_source.json"
OUTPUT = ROOT / "include" / "demake" / "generated" / "scene_asset_data.hpp"
ZONE_ORDER = ("interior", "vista", "arena")
BLOB_OUTPUTS = {zone: ROOT / "romfs" / "zones" / f"{zone}.bin" for zone in ZONE_ORDER}
BLOB_HEADER = struct.Struct("<4sHHI")
BLOB_RECORD = struct.Struct("<10fbbB")


def normalize_box(raw: dict, name: str, x_offset: float = 0.0, z_offset: float = 0.0,
                  rotation: float = 0.0) -> dict:
    position = raw["position"]
    scale = raw["scale"]
    color = raw["color"]
    x = float(position[0]) + x_offset
    z = float(position[2]) + z_offset
    return {
        "name": name,
        "x": x,
        "y": float(position[1]),
        "z": z,
        "sx": float(scale[0]),
        "sy": float(scale[1]),
        "sz": float(scale[2]),
        "rotation": float(raw.get("rotation_y", rotation)),
        "red": float(color[0]),
        "green": float(color[1]),
        "blue": float(color[2]),
        "cell_x": max(-127, min(127, math.floor(x / 6.0))),
        "cell_z": max(-127, min(127, math.floor(z / 6.0))),
        "always": bool(raw.get("always", False)),
    }


def expand_zone(zone: dict) -> list[dict]:
    boxes = [normalize_box(raw, raw["name"]) for raw in zone.get("boxes", [])]
    for generator in zone.get("generators", []):
        kind = generator["type"]
        if kind == "mirrored_line":
            for side in (-1.0, 1.0):
                for z in generator["z_values"]:
                    for index, template in enumerate(generator["templates"]):
                        boxes.append(normalize_box(
                            template,
                            f"{generator['name']}_{int(side)}_{z}_{index}",
                            side * float(generator["x"]),
                            float(z),
                        ))
        elif kind == "alternating_path":
            for index in range(int(generator["count"])):
                side = -1.0 if index % 2 == 0 else 1.0
                x = side * (float(generator["x_base"]) + (index * 3) % int(generator["x_modulus"]))
                z = float(generator["start_z"]) + index * float(generator["step_z"])
                for template_index, template in enumerate(generator["templates"]):
                    boxes.append(normalize_box(
                        template, f"{generator['name']}_{index}_{template_index}", x, z
                    ))
        elif kind == "radial":
            count = int(generator["count"])
            radius = float(generator["radius"])
            for index in range(count):
                angle = index / count * math.tau
                boxes.append(normalize_box(
                    generator["template"],
                    f"{generator['name']}_{index}",
                    math.sin(angle) * radius,
                    math.cos(angle) * radius,
                    angle,
                ))
        else:
            raise ValueError(f"unsupported scene generator {kind!r}")
    return sorted(boxes, key=lambda box: (box["cell_z"], box["cell_x"], box["name"]))


def format_float(value: float) -> str:
    if abs(value) < 0.0000005:
        value = 0.0
    return f"{value:.6f}f"


def generate() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/convert_scene_assets.py. Do not edit by hand.",
        "namespace demake::generated {",
    ]
    for zone_id in ZONE_ORDER:
        boxes = expand_zone(data["zones"][zone_id])
        symbol = zone_id.title()
        lines.append(f"inline constexpr SceneBox k{symbol}Boxes[] = {{")
        for box in boxes:
            values = [
                box["x"], box["y"], box["z"], box["sx"], box["sy"], box["sz"],
                box["rotation"], box["red"], box["green"], box["blue"],
            ]
            fields = ", ".join(format_float(value) for value in values)
            always = "true" if box["always"] else "false"
            lines.append(
                f"    {{{fields}, {box['cell_x']}, {box['cell_z']}, {always}}},"
            )
        lines.append("};")
        lines.append(
            f"inline constexpr std::size_t k{symbol}BoxCount = "
            f"sizeof(k{symbol}Boxes) / sizeof(k{symbol}Boxes[0]);"
        )
        lines.append("")
    lines.extend(["} // namespace demake::generated", ""])
    return "\n".join(lines)


def generate_blob(zone_id: str, boxes: list[dict]) -> bytes:
    payload = bytearray(BLOB_HEADER.pack(b"ASZN", 1, BLOB_RECORD.size, len(boxes)))
    for box in boxes:
        payload.extend(
            BLOB_RECORD.pack(
                box["x"], box["y"], box["z"], box["sx"], box["sy"], box["sz"],
                box["rotation"], box["red"], box["green"], box["blue"],
                box["cell_x"], box["cell_z"], 1 if box["always"] else 0,
            )
        )
    return bytes(payload)


def generate_blobs() -> dict[str, bytes]:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    return {
        zone_id: generate_blob(zone_id, expand_zone(data["zones"][zone_id]))
        for zone_id in ZONE_ORDER
    }


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = generate()
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != payload:
        OUTPUT.write_text(payload, encoding="utf-8")
    blobs = generate_blobs()
    for zone_id, blob in blobs.items():
        output = BLOB_OUTPUTS[zone_id]
        output.parent.mkdir(parents=True, exist_ok=True)
        if not output.exists() or output.read_bytes() != blob:
            output.write_bytes(blob)
    outputs = ", ".join(str(BLOB_OUTPUTS[zone].relative_to(ROOT)) for zone in ZONE_ORDER)
    print(f"generated {OUTPUT.relative_to(ROOT)} and {outputs}")


if __name__ == "__main__":
    main()
