#!/usr/bin/env python3
"""Generate a fixed-size C++ asset registry from validated authored manifests."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "assets" / "manifest.json"
OUTPUT = ROOT / "include" / "demake" / "generated" / "asset_registry_data.hpp"
ZONE_ORDER = ("interior", "vista", "arena")


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate() -> str:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    assets = sorted(manifest["assets"], key=lambda item: item["id"])
    zone_paths = manifest["zone_manifests"]
    zones = [json.loads((ROOT / zone_paths[zone]).read_text(encoding="utf-8")) for zone in ZONE_ORDER]

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/generate_asset_registry.py. Do not edit by hand.",
        "namespace demake::generated {",
        "inline constexpr AssetRecord kAssets[] = {",
    ]
    for asset in assets:
        zone_mask = sum(1 << ZONE_ORDER.index(zone) for zone in asset["zones"])
        lines.append(
            "    {"
            f"{cpp_string(asset['id'])}, {cpp_string(asset['kind'])}, "
            f"{cpp_string(asset['output'])}, {int(asset['max_bytes'])}U, {zone_mask}U"
            "},"
        )
    lines.extend([
        "};",
        "inline constexpr std::size_t kAssetCount = sizeof(kAssets) / sizeof(kAssets[0]);",
        "",
        "inline constexpr ZoneAssetRecord kZones[] = {",
    ])
    for zone in zones:
        lines.append(
            "    {"
            f"{cpp_string(zone['id'])}, {cpp_string(zone['display_name'])}, "
            f"{int(zone['runtime_budget_bytes'])}U, {int(zone['romfs_budget_bytes'])}U, "
            f"{int(zone['draw_call_budget'])}U, {len(zone['assets'])}U"
            "},"
        )
    lines.extend([
        "};",
        "inline constexpr std::size_t kZoneCount = sizeof(kZones) / sizeof(kZones[0]);",
        "} // namespace demake::generated",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    payload = generate()
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != payload:
        OUTPUT.write_text(payload, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
